import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { TopbarUI } from '@/widgets/topbar';
import { HeaderUI } from '@/widgets/header';

import { Container } from '@/shared/components/container';
import { NavigationUI } from '@/widgets/navigation';
import { ToastUI } from '@/shared/components/toast';
import { ReactNode } from 'react';
import { AuthProvider } from '@/features/auth';
import { Footer } from '@/widgets/footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {

  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <AuthProvider>
      <div>
        <TopbarUI />
        <HeaderUI />
        <NavigationUI />
      </div>
      <main>
        <Container>
          {children}
        </Container>
        <ToastUI />
      </main>
      <Footer />
    </AuthProvider>
    </body>
    </html>
  );
}
